### ISSUE TITLE
Train model error:  

### ISSUE THREAD

**Issue by susan987321** [Microsoft/AutonomousDrivingCookbook#105]
When I tried to train the model, run this line
data_generator = DriveDataGenerator(rescale=1./255., horizontal_flip=True, brighten_range=0.4)
I got an error:

  File "D:\ProgramData\Anaconda\lib\site-packages\keras_preprocessing\image\image_data_generator.py", line 362, in __init__
    'Received: %s' % (brightness_range,))

ValueError: `brightness_range should be tuple or list of two floats. Received: 0.0

It seems it needs more parameters.
How to correct it? Thank you very much!

**Comment by weigangwen** [comment]
Hello, I have encountered the same problem. Have you solved this problem?Thanks a lot！
