### ISSUE TITLE
When sending the  steering angle to Carclient ,should the predition angle multiply 0.69 ?

### ISSUE THREAD

**Issue by weigangwen** [microsoft/AutonomousDrivingCookbook#119]
## Problem description
In AirsimE2EDeeplearning, we use the trained model to predict the steering angle for  car-controls, should the predition angle (the model's  output)-multiply 0.69 ?

## Problem details
In TrainModel.ipynb,I have noticed that the steering angle is described in draw_image_with_label(img, label, prediction=None) function   by this:

theta = label * 0.69    #Steering range for the car is +- 40 degrees -> 0.69 radians

the prediction :

theta = prediction * 0.69

so ,my question is :In TestModel.ipynb,

car_controls.steering = round( float(model_output[0][0]), 2)
print('Sending steering = {0}, throttle = {1}'.format(car_controls.steering, car_controls.throttle))
 
the model's output should multiply 0.69?

**Comment by DanHateCoding** [comment]
Have you solved this problem? And could you please provide the solution?
