### ISSUE TITLE
GPU memory error (with solution)

### ISSUE THREAD

**Issue by edimoon777** [Microsoft/AutonomousDrivingCookbook#17]
## Problem description
To run TestModel.ipynb using the GPU with small memory such as GTX1060 6GB.
Memory error comes out like below.

## Problem details
Error message looks like below.
***
~\cuda\cuda_blas.cc:443] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
~\cuda\cuda_blas.cc:443] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
~\cuda\cuda_blas.cc:443] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
~\cuda\cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
~\cuda\cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
~\tensorflow\core\kernels\conv_ops.cc:717] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)
***

## Solution
This error is related with lack of memory.
Add this code in TestModel.ipynb.

`import tensorflow as tf  `  
`config = tf.ConfigProto()`    
`config.gpu_options.allow_growth = True  `  
`sess = tf.Session(config=config) `   

If you want to know details about solutions, please see answers from nVidia :  
 https://devtalk.nvidia.com/default/topic/1021858/jetson-tx2/tensorflow-memory-error/1

**Comment by mitchellspryn** [comment]
Now that you mention this, I think I recall running into this before. That code works, but it marries the code to the tensorflow backend. Rather than include it in the notebook, we can make a note that it could potentially solve this issue.
