### ISSUE TITLE
AirSimClient.py missing

### ISSUE THREAD

**Issue by mitchellspryn** [Microsoft/AutonomousDrivingCookbook#3]
AirSimClient.py is missing from the repo. This will lead to an import error when attempting to run the model. 

The fix is in [this PR](https://github.com/Microsoft/AutonomousDrivingCookbook/pull/2). This will be merged shortly, but if you are in a hurry, the branch E2EDL_Bugfixes can be pulled.

**Comment by adshar** [comment]
Merged. Closing issue.
