### ISSUE TITLE
Cannot use segmentation images as data set.

### ISSUE THREAD

**Issue by BrianN92** [Microsoft/AutonomousDrivingCookbook#31]
Because the shadow of trees in "Neighborhood" often causes confused, I tried to use the segmentation images recorded as training data set. However, the car cannot move properly during testing. I am wondering whether I can train it by segmentation images or not?

**Comment by shrimalmadhur** [comment]
I believe that map is not that great for segmentation since the mesh of road and the side walk is the same, so when you get the segmentation and train on that, you might loose features which the side walk also provides. I guess if the map has better segmentation you could train a better model but still normal RGB image has more deep features than segmentation.

**Comment by shrimalmadhur** [comment]
Yup. I agree good segmentation image can be helpful. Maybe there's way we can utilize both of them, so that we get good features from RGB and use the segmentation to solve the shadow issue.

**Comment by mitchellspryn** [comment]
@BrianN92 What, precisely, are you trying to do? Are you trying to train the end-to-end model on a dataset you collected from the neighborhood map?

**Comment by BrianN92** [comment]
@mitchellspryn Yes, I am trying to train the E2E model on the neighborhood map. Sorry for the vagueness of this question.

**Comment by mitchellspryn** [comment]
Ok. In that case, using the segmentation images as input to your model is suspicious. Consider that in a real scenario, your vehicle will not have access to the segmentation images. By requiring that as an input to your net, you'd be developing a model that only works in a simulator and would not translate to the real world.

A more generalizable approach would be to create a transformation that adds random patches of shadows on existing images. A simple way of doing this could be to select a random set of connected pixels from the RGB image, transform the pixel to HSV space, decrease the value by a set multiplier (i.e. 'value = value * 0.9'), and transforming back to RGB space. By doing this, the model will learn that the shadows don't really mean anything, and will become more robust to the noise.

**Comment by BrianN92** [comment]
Thanks, I will try it!

**Comment by BrianN92** [comment]
Hi @mitchellspryn , after the image transformation, like the images I attached below, I have another question.
![img_0_0_341742162365](https://user-images.githubusercontent.com/21299740/38621280-8a18f978-3d6e-11e8-96a1-7d463524f18d.png)
![image-1](https://user-images.githubusercontent.com/21299740/38621285-8f5b8838-3d6e-11e8-94b0-15b0580aa847.png)

How can I make the names of images after transformation corresponding to the "ImageName" tag in every "airsim_rec.txt" file? Thank you!

**Comment by mitchellspryn** [comment]
I assume you wrote another script that created the transformations? If so, you'll probably be better off directly generating the .h5s for training. Look in "cooking.py" and mimic that logic in your preprocessing script. 

In fact, if you really wanted to get slick, you could probably add this as an additional transform inside of Generator.py. You'll see the set of transforms we've already coded inside of random_transform_with_states(); you can just add yours there.
