### ISSUE TITLE
How to generate new dataset?

### ISSUE THREAD

**Issue by lyhbuaa** [Microsoft/AutonomousDrivingCookbook#41]
**Your issue may already be reported! Please make sure to search all open and closed issues before starting a new one.**

Please fill out the sections below so we can understand your issue better and resolve it quickly.

## Problem description
*I have finished the tutorial used the official dataset, now Iwant to add some test example to the dataset, I don‘t know how to collect the control data corresponding to the picture, Is there a tutorial? thanks a lot!’*

## Problem details
*(Please describe your problem in as much detail as possible here. Make sure to include screenshots, code snippets, error messages, links and anything else you think will help us understand your problem better. If applicable, please also provide us a list of steps to reproduce your problem.)*

## Exepriment/Environment details
* Tutorial used: *(For example, AirSimE2EDeepLearning, DistributedRL etc.)*
* Environment used: *(For example, landscape, city, hawaii etc.)*
* Versions of artifacts used (if applicable): *(For example, Python 3.5, Keras 2.1.2 etc.)*

**Comment by mitchellspryn** [comment]
IIRC, I just used the record feature. Click the red record button (or I think it's bound to 'r') to start recording. The images and airsim_rec.txt will be recorded in the same directory that contains your settings.json.

**Comment by abc19850508** [comment]
ok, thanks you! I will try it!
