### ISSUE TITLE
AD_Cookbook_Start_AirSim.ps1 crash

### ISSUE THREAD

**Issue by cl3m3nt** [Microsoft/AutonomousDrivingCookbook#44]
**Your issue may already be reported! Please make sure to search all open and closed issues before starting a new one.**

Please fill out the sections below so we can understand your issue better and resolve it quickly.

## Problem description
AD_Cookbook_Start_AirSim.ps1 crash

## Problem details
When trying to launch **AD_Cookbook_Start_AirSim.ps1 landscape** the program crash with the following error message: 
Fatal Error !
The UE4-JustAssets Game has crashed 
When trying to launch **AD_Cookbook_Start_AirSim.ps1 city** the program crash with the following error message: 
DX11 feature level 10.0 is required to run the engine

## Exepriment/Environment details
* Tutorial used: AirSimE2EDeepLearning
* Environment used:  landscape, city
* System config: 
NC6 Azure VM with Tesla K80 NVIDIA GPU, Windows Server2016 Datacenter 10.0.14393 Build 14393
K80 Driver Version: 22.21.13.8628
DirectX: DirectX12

**Comment by mitchellspryn** [comment]
This won't work on the NC machines. This is due to the licensing model imposed by NVIDIA. You need a NV.
