### ISSUE TITLE
EndtoEnd exercise answers

### ISSUE THREAD

**Issue by laoji525** [microsoft/AutonomousDrivingCookbook#52]
You leave some exercise questions. I tried to think about these. Is my thinking correct?

`Thought Exercise 1.1 Try playing around with these parameters to see if you can get better results.
`
I think we could change Zero_Drop_Percentage to a smaller number as 0.85 to bring a little bit more data to model training.
Brigthen_Range could be bigger like 0.5 to make the model distinguish road and some other white environment stuff better.
I changed ROI value and found 76,135,0,255 is the optimized value.

``
Thought Exercise 2.1: As you might have noticed, the motion of the car is not very smooth on those bridges. Can you think of a reason why it is so? Can you use one of the techniques we described in Step 0 to fix this?
``
I did notice the car run badly on bridges. I did not come up with the reason. 

``
Thought Exercise 2.2: The car seems to crash when it tries to climb one of those hills. Can you think of a reason why? How can you fix this? (Hint: You might want to take a look at what the car is seeing when it is making that ascent)
``
I see the car crashed the same place of a small hill all the time. I check the camera image at that time. I think the road looks too similiar with the rocks at that moment. We could change the brightness value when training model.

**Comment by mitchellspryn** [comment]
Hi @laoji525 

Thanks for running the tutorial! I can see that you've thought about these questions quite a bit. I do have some comments on your answers, but I'm hesitant to post them here as I don't want to spoil the answers for others as well (@adshar @shrimalmadhur, thoughts?)

Shoot me an email at mspryn@microsoft.com, and we can discuss.

**Comment by adshar** [comment]
I agree. It is probably best to not post the answers here. Feel free to shoot an email though, would love to talk more. About the new ROI value, did you see improvement to your trained models? Do you mind elaborating on improvement you saw?
