### ISSUE TITLE
Launch local training job in DistributedRL

### ISSUE THREAD

**Issue by e271141** [Microsoft/AutonomousDrivingCookbook#56]
I launch the train.bat for Reinforcement learning. The car may occasionally tumbling on the ground or rotating in air for each new epoch. I tried to fix this by modify the distributed_agent.py. In function __get_next_starting_point() I set "random_direction=(0,0,0)", but it doesn't work.  What is the cause of this problem?
![rotate](https://user-images.githubusercontent.com/16033465/42083486-9d0ba7b4-7bbd-11e8-983a-7501a9e88085.png)

## Exepriment/Environment details
* Tutorial used: AirSimE2EDeepLearning, DistributedRL
* Environment used: Neighborhood

**Comment by e271141** [comment]
Ok, I figure it out myself. As it turns out, the Z direction points down the surface. We should set the starting point as -1 or some minus number to make sure the car won't get stuck in the road.

**Comment by Curry30h** [comment]
hello，can you tell me how should I modify the code in distributed_agent.py so that it can be trained locally? Thank you.
