### ISSUE TITLE
 max() arg is an empty sequence

### ISSUE THREAD

**Issue by vighnesh-balaji** [Microsoft/AutonomousDrivingCookbook#59]
Traceback (most recent call last):
  File "Test.py", line 17, in <module>
    best_model = max(models, key=os.path.getctime)
ValueError: max() arg is an empty sequence

The model was trained with an error of 0.00022 
but testing the model throws this error

**Comment by mitchellspryn** [comment]
Please use the issue template when reporting issues. It gives us the needed information to help solve your problem. For example, what version of keras / tensorflow / python / numpy / pandas are you using?

**Comment by mitchellspryn** [comment]
Probably a duplicate of this one. https://github.com/Microsoft/AutonomousDrivingCookbook/issues/63.
