### ISSUE TITLE
UE4 error: GameThread timed out waiting for RenderThread after 30.03 secs

### ISSUE THREAD

**Issue by NextSim** [Microsoft/AutonomousDrivingCookbook#62]
## Problem description
When training data in the neighborhood environment provided in the tutorials, Unreal can crash with the error:

Fatal error:
[FileF:\UnrealEngine\UnrealEngine\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp][Line:994]
GameTherad timed out waiting for RenderThread after 30.03 secs

## Problem details
I'm running the training on a Windows PC with an NVIDIA GeForce GTX 980 Ti.

It looks like this was already fixed in more recent AirSim environments:

https://github.com/Microsoft/AirSim/issues/797

What is modified in the neighborhood environment for the tutorials?  Or is it just using a specific version of airsim that is compatible with the tutorials, so updating the environment would mean updating the tutorials?

## Exepriment/Environment details
* Tutorial used:  DistributedRL
* Environment used: neighborhood

**Comment by mitchellspryn** [comment]
We built our binaries with an older version of AirSim, and we have been recommending the use of this for API stability (e.g. https://github.com/Microsoft/AutonomousDrivingCookbook/issues/60). I haven't ever seen this issue. If you continuously run into it, you may try the official binaries - I don't think there is much difference for the neighborhood environment.
