### ISSUE TITLE
Driving in the center of lane

### ISSUE THREAD

**Issue by NextSim** [Microsoft/AutonomousDrivingCookbook#69]
## Problem description
I'm trying to think of a way to teach the car to drive in the center of the lane, as opposed to the center of the road.   For the neighborhood environment the center of the road makes sense, because of the cars, but also for demonstration of the capabilities, but ideally it would be trained to drive in the center of the road.

## Problem details
So I'm wondering if anyone has worked on this?

I was thinking it may be possible to lay out the road lines always in the right lane, and then determine an offset for the road line between the left and right lane.  Depending on the orientation of the car, it could apply the offset to the road line so it is driving on the correct side of the road.

I'm not sure how this would affect turning, or roads with more than one lane... but I thought it may be a start.

## Experiment/Environment details
* Tutorial used: Distributed RL
* Environment used: Custom

**Comment by mitchellspryn** [comment]
That seems like a reasonable approach. The tricky part is that the "right" lane will now depend on which way you are facing. Consider that if you are driving on a north-south road, the "right" lane going north is different than the "right" lane going south, so your reward function will have to take that into account as well.
