### ISSUE TITLE
Use Tensorboard to visualize training

### ISSUE THREAD

**Issue by NextSim** [Microsoft/AutonomousDrivingCookbook#72]
## Problem description
I thought it would be helpful to visualize what is going on in the training with Tensorboard.  But I don't know what variables to view or where to find them

## Problem details
I have Tensorboard set up so I can see the architecture, but I'm not sure what values would be useful to visualize, or what files they are in. I can graph the reward calculated in __compute_reward, but this is the reward calculated each frame, correct? I added a summary scalar to it, but it creates a different graph for each run, it doesn't show on one graph. 

How can I visualize if the algorithm is getting better, except that the reward each frame should increase over time?

What other values would be helpful to visualize?

Thanks

## Experiment/Environment details
* Tutorial used: DistributedRL
* Environment used: Neighborhood

**Comment by mitchellspryn** [comment]
I'd recommend looking at the following:

1) Average episode length.
2) Average reward (over multiple episodes). 
3) Average magnitude of the gradient. This should go down over time as the model converges.
