### ISSUE TITLE
Is there a drones AutonomousDrivingCookbook?

### ISSUE THREAD

**Issue by LeroyLK** [Microsoft/AutonomousDrivingCookbook#81]
I have searched many repositories in Github, but only find two: one is this, however is for car; another is https://github.com/AirSimDroneSimulator/AirSim, however it's codes can't run successfully!
So I am very eager to know if there is a rep. of Autonomous drones?

**Comment by mitchellspryn** [comment]
AFAIK no. However, there are some sample scripts in the [Airsim Docs](https://github.com/Microsoft/AirSim/tree/master/docs) that might get you started.
