### ISSUE TITLE
eval.h5 & test.h5 datasets not generated in data_cooked directory

### ISSUE THREAD

**Issue by tfromb** [Microsoft/AutonomousDrivingCookbook#91]
Im doing the E2EDeepLearning tutorial. When I try to read in the datasets in TrainModel from the exploration phase, the eval.h5 and test.h5 files are not generated and so can not be opened. I've gone back to the DataExploration phase and run the code, however, they still aren't generating. I received a StopIteration as shown below. How can I fix this?

Thanks

`StopIteration                             Traceback (most recent call last)
~\Documents\Tomi\AirSim\AutonomousDrivingCookbook-master\AirSimE2EDeepLearning\Cooking.py in generatorForH5py(data_mappings, chunk_size)
    129                 raise StopIteration
--> 130     raise StopIteration
    131 

StopIteration: 

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-28-bce568193587> in <module>
      1 train_eval_test_split = [0.7, 0.2, 0.1]
      2 full_path_raw_folders = [os.path.join(RAW_DATA_DIR, f) for f in DATA_FOLDERS]
----> 3 Cooking.cook(full_path_raw_folders, COOKED_DATA_DIR, train_eval_test_split)

~\Documents\Tomi\AirSim\AutonomousDrivingCookbook-master\AirSimE2EDeepLearning\Cooking.py in cook(folders, output_directory, train_eval_test_split)
    196         for i in range(0, len(split_mappings), 1):
    197             print('Processing {0}...'.format(output_files[i]))
--> 198             saveH5pyData(split_mappings[i], output_files[i])
    199             print('Finished saving {0}.'.format(output_files[i]))

~\Documents\Tomi\AirSim\AutonomousDrivingCookbook-master\AirSimE2EDeepLearning\Cooking.py in saveH5pyData(data_mappings, target_file_path)
    162         dset_previous_state[:] = previous_state_chunk
    163 
--> 164         for image_names_chunk, label_chunk, previous_state_chunk in gen:
    165             image_chunk = np.asarray(readImagesFromPath(image_names_chunk))
    166 

RuntimeError: generator raised StopIteration`

**Comment by wonjoonSeol** [comment]
It works fine for me, check if you are using Keras 2.1.2, you cannot use newer version of Keras on AirSimE2EDeepLearning. It should be written on the readme really. I will update..

**Comment by mitchellspryn** [comment]
Are you on python 3.7? [If so, that's your issue](https://github.com/Microsoft/AutonomousDrivingCookbook/issues/94).
