### ISSUE TITLE
How to download the AD COOKBOOK AIRSIM by AzCopy?

### ISSUE THREAD

**Issue by ZhoubinXM** [Microsoft/AutonomousDrivingCookbook#95]
Hi,
When I use AzCopy to download the Package, it has the error above：
![image](https://user-images.githubusercontent.com/44090409/54576194-1903a400-4a32-11e9-8e6f-2ad9f9c3ceb2.png)

**Comment by CrookedNoob** [comment]
You don't need source key
remove the part /SoursceKey:key /S /V

**Comment by mitchellspryn** [comment]
@CrookedNoob is right. This is a public dataset, so we don't have any authentication turned on.
