### ISSUE TITLE
Is is possible to get more data?

### ISSUE THREAD

**Issue by CrookedNoob** [Microsoft/AutonomousDrivingCookbook#99]
I have trained with my own network and it is working fine. The car is able to drive almost half the distance but after that it is not able to differentiate between the snow and the road due to the sunlight reflection on the map. Is it possible to get more data to train the network better?

**Comment by mitchellspryn** [comment]
Sure. You can use the python API to record more data from the front facing webcam to augment the training dataset. You'd need to add them to the data_raw folder, and modify the first notebook to pick up the new data.

**Comment by CrookedNoob** [comment]
Got it!! Thanks for the input!!
